name: Deploy to VMs

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-on-vm:
    runs-on: self-hosted

    strategy:
      matrix:
        #  creates two parallel runs of this job
        instance: [1, 2]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Execute deployment script
        env:
          PORT_FROM_SECRET: ${{ secrets.NODE_TCP_PORT }}
        run: |
          chmod +x deploy.sh
          ./deploy.sh

