name: Destroy Services

on:
  # allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  destroy:
    name: Stop and Remove Services from VMs
    runs-on: self-hosted
    
    # use a matrix strategy to run the job multiple times
    strategy:
      matrix:
        #  creates two parallel runs of this job
        instance: [1, 2]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Destruction Script
        run: |
          chmod +x teardown.sh
          ./teardown.sh